### ISSUE TITLE
rule.h protocol

### ISSUE THREAD

**Issue by hollybertolet** [Muhlenberg/mfw#11]
Why did you make protocol uint8_t? What values are corresponding with All/UDP/TCP, can it just be an enum like action and direction?

**Comment by benburwell** [comment]
See the list of [protocol numbers](https://www.iana.org/assignments/protocol-numbers/protocol-numbers.xhtml). It should be one of these. TCP=6, UDP=17.

I think @maborowsky and I discussed using `-1` or `0` for all... Mike?

**Comment by hollybertolet** [comment]
0 has a protocol so it would probably be best to use -1 
or we could use something greater than 255, that appears to be the largest value

**Comment by benburwell** [comment]
Well either way, we'll have to change the code, either to `int8_t` or `uint16_t`, since neither -1 or anything greater than 255 can be stored in a `uint8_t`... an oversight on my part. Using `-1` and changing it to `int8_t` kind of makes the most sense to me...
